version: '3'
services:
  release-tracker-service:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB_URL: jdbc:postgresql://postgres-db/release-tracker-db
      POSTGRES_USER: release-tracker-user
      POSTGRES_PASSWORD: release-tracker-password
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: release-tracker-db
      POSTGRES_USER: release-tracker-user
      POSTGRES_PASSWORD: release-tracker-password