version: '3'
services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'